import os

OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
RECEIVER_EMAIL = os.getenv("RECEIVER_EMAIL")
AWS_SES_USER = os.getenv("AWS_SES_USER")
AWS_SES_PASS = os.getenv("AWS_SES_PASS")
SMTP_SERVER = os.getenv("SMTP_SERVER")